//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto1_Juan_Palacios.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Show
    {
        public int ID_Show { get; set; }
        public string NombreShow { get; set; }
        public System.DateTime Fecha_Evento { get; set; }
        public string HoraEvento { get; set; }
        public int Cantidad { get; set; }
        public Nullable<int> ID_Artista { get; set; }
        public Nullable<int> ID_Encargado { get; set; }
        public Nullable<int> ID_Grupo { get; set; }
    
        public virtual Artista Artista { get; set; }
        public virtual EncargadoEvento EncargadoEvento { get; set; }
        public virtual Grupos Grupos { get; set; }
    }
}
